#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: main
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get swig libboost-system-dev build-essential quilt clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo apt-get autoremove --purge
        sudo apt-get clean
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update feeds url
      run: |
        cd openwrt
        sed -i -E 's;git.openwrt.org/(feed|project);github.com/openwrt;' feeds.conf.default

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cd openwrt
        wget https://raw.githubusercontent.com/ramonmodesto99999/Actions-OpenWrt/refs/heads/main/.config 

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: patchs bbrv3
      id: bbrv3
      run: |
        cd openwrt
        cd target/linux/generic/hack-6.12/

        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0001-net-tcp_bbr-broaden-app-limited-rate-sample-detectio.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0002-net-tcp_bbr-v2-shrink-delivered_mstamp-first_tx_msta.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0003-net-tcp_bbr-v2-snapshot-packets-in-flight-at-transmi.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0004-net-tcp_bbr-v2-count-packets-lost-over-TCP-rate-samp.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0005-net-tcp_bbr-v2-export-FLAG_ECE-in-rate_sample.is_ece.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0006-net-tcp_bbr-v2-introduce-ca_ops-skb_marked_lost-CC-m.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0007-net-tcp_bbr-v2-adjust-skb-tx.in_flight-upon-merge-in.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0008-net-tcp_bbr-v2-adjust-skb-tx.in_flight-upon-split-in.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0009-net-tcp-add-new-ca-opts-flag-TCP_CONG_WANTS_CE_EVENT.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0010-net-tcp-re-generalize-TSO-sizing-in-TCP-CC-module-AP.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0011-net-tcp-add-fast_ack_mode-1-skip-rwin-check-in-tcp_f.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0012-net-tcp_bbr-v2-record-app-limited-status-of-TLP-repa.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0013-net-tcp_bbr-v2-inform-CC-module-of-losses-repaired-b.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0014-net-tcp_bbr-v2-introduce-is_acking_tlp_retrans_seq-i.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0015-tcp-introduce-per-route-feature-RTAX_FEATURE_ECN_LOW.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0016-net-tcp_bbr-v3-update-TCP-bbr-congestion-control-mod.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0017-net-tcp_bbr-v3-ensure-ECN-enabled-BBR-flows-set-ECT-.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0018-tcp-export-TCPI_OPT_ECN_LOW-in-tcp_info-tcpi_options.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/a7ffdcae8e96eb6dece70622de121f97ff55bfab/target/linux/generic/hack-6.12/952-bbr3-0019-x86-cfi-bpf-Add-tso_segs-and-skb_marked_lost-to-bpf_.patch
        wget https://raw.githubusercontent.com/rockdrilla/fork.openwrt/e2fa1c32f89ec0bfb726ceb96294b6b957b32d67/target/linux/generic/hack-6.12/952-bbr3-0100-krd-32-bit-fixes.patch

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc)
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
